# Generated by Django 3.2.4 on 2021-06-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alora', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
